# Generated by Django 3.0.4 on 2020-03-18 22:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('trabajador', '0001_initial'),
        ('comun', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_venta', models.IntegerField(blank=True, null=True, verbose_name='No de venta')),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='Fecha emision')),
                ('total', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total')),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comun.Tipopago')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajador.Trabajador')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'vale',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canti', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('descuento', models.FloatField(choices=[(1.0, '0%'), (0.95, '5%'), (0.9, '10%'), (0.85, '15%'), (0.8, '20%'), (0.75, '25%'), (0.7, '30%'), (0.65, '35%'), (0.6, '40%'), (0.55, '45%'), (0.5, '50%')], default=1.0, null=True, verbose_name='Descuento')),
                ('subtotal', models.FloatField(blank=True, editable=False, null=True, verbose_name='Subtotal')),
                ('id_prod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Producto', to='producto.Producto')),
                ('id_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='venta.Venta')),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalle de ventas',
                'db_table': 'detalle_venta',
            },
        ),
    ]
